name: "Build component"
description: "Build component by the name specified in input parameters"
inputs:
  component_name:
    description: "Component name"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout
      if: inputs.component_name != ''
      uses: actions/checkout@v3
    - name: Update PYTHONPATH
      if: inputs.component_name != ''
      run: echo "PYTHONPATH=/home/runner/work/gha/gha" >> $GITHUB_ENV
      shell: bash
    - name: Build component
      if: inputs.component_name != ''
      run: python src/runner.py build component ${{ inputs.component_name }}
      shell: bash
