name: Build pipeline

on:
  workflow_call:
    inputs:
      pipeline_name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Build the pipeline"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update PYTHONPATH
        run: echo "PYTHONPATH=/home/runner/work/gha/gha" >> $GITHUB_ENV
      - name: Build the pipeline
        run: python src/runner.py build pipeline ${{ inputs.pipeline_name }}
