name: Build c2 component

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - "master"
    paths:
      - "src/components/component2.yaml"

jobs:
  build_c2:
    uses: ./.github/workflows/build_component.yml
    with:
      component_name: "c2"
  build_p2:
    uses: ./.github/workflows/build_pipeline.yml
    with:
      pipeline_name: "p2"
