name: Build p2 pipeline

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - "master"
    paths:
      - "src/pipelines/pipeline2.yaml"

jobs:
  build:
    uses: ./.github/workflows/build_pipeline.yml
    with:
      pipeline_name: "p2"
