name: Check how IF affects NEEDS

on:
  pull_request:
    types:
      - closed
    branches:
      - "master"
    paths:
      - "src/**"

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo The PR was mergedgit_diff:
  git_diff:
    needs: if_merged
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: Get diff
        run: git diff --name-only origin/master origin/${GITHUB_REF}