name: Build changed components and pipelines

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - "master"
    paths:
      - "src/**"

jobs:
  git_diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get diff
        run: git diff --name-only origin/master origin/${GITHUB_HEAD_REF}
      - name: Save diff to env
        run: echo "GIT_DIFF=$(echo (git diff --name-only origin/master origin/${GITHUB_HEAD_REF}))" >> $GITHUB_ENV
      - name: Check env
        run: echo $GIT_DIFF
  build_components:
    needs: git_diff
    strategy:
      matrix:
        name: [ "c1", "c2", "c3" ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build component
        uses: ./.github/actions/build_component
        with:
          component_name: ${{ matrix.name }}
  build_pipelines:
    needs: build_components
    strategy:
      matrix:
        name: [ "p1", "p2" ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build pipeline
        uses: ./.github/actions/build_pipeline
        with:
          component_name: ${{ matrix.name }}
